name: Deploy to VPS

on:
  push:
    branches: 'main'

env:
  SSH_KEY: '${{ secrets.SSH_KEY }}'

jobs:
  build_site:
    runs-on: docker
    steps:
      - name: Deploy
        run: |
          TEMP_PATH="$(mktemp -d)"
          SSH_KEY_PATH="$TEMP_PATH/ssh_key"
          echo "$SSH_KEY" > "$SSH_KEY_PATH"
          chmod 600 "$SSH_KEY_PATH"
          cat > deploy.sh << EOF
          cd ~/loops-web
          git pull
          corepack pnpm i --frozen-lockfile
          corepack pnpm run build
          systemctl --user restart loops-web
          EOF
          ssh -o "StrictHostKeyChecking no" "${{ secrets.SSH_HOST }}" -p "${{ secrets.SSH_PORT || 22 }}" -l "${{ secrets.SSH_USER }}" -i "$SSH_KEY_PATH" 'bash -s' < deploy.sh
          rm -rf $TEMP_PATH
